<?php

namespace Proxies\__CG__\uni\bundle\superhBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class superheroe extends \uni\bundle\superhBundle\Entity\superheroe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'id', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'nombre', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'descripcion', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'habilidades', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'edad', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'sexo', 'tipo', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'zona');
        }

        return array('__isInitialized__', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'id', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'nombre', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'descripcion', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'habilidades', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'edad', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'sexo', 'tipo', '' . "\0" . 'uni\\bundle\\superhBundle\\Entity\\superheroe' . "\0" . 'zona');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (superheroe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setHabilidades($habilidades)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHabilidades', array($habilidades));

        return parent::setHabilidades($habilidades);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabilidades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabilidades', array());

        return parent::getHabilidades();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdad($edad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdad', array($edad));

        return parent::setEdad($edad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdad', array());

        return parent::getEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', array($sexo));

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', array());

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(\uni\bundle\superhBundle\Entity\tipos $tipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function addZona(\uni\bundle\superhBundle\Entity\zonas $zona)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addZona', array($zona));

        return parent::addZona($zona);
    }

    /**
     * {@inheritDoc}
     */
    public function removeZona(\uni\bundle\superhBundle\Entity\zonas $zona)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeZona', array($zona));

        return parent::removeZona($zona);
    }

    /**
     * {@inheritDoc}
     */
    public function getZona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZona', array());

        return parent::getZona();
    }

}
